Develop
AlexMAK1/java-explore-with-me pull request #1
Opened 2022-11-05 16:45 UTC by AlexMAK1

begining

2022-11-07 12:29 UTC, krylov-sergey-sergeevich requested changes

2022-11-07 12:29 UTC, krylov-sergey-sergeevich commented on main_service/Dockerfile
> +COPY target/*.jar app.jar
Можно еще вот так:
```
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
```

2022-11-07 12:29 UTC, krylov-sergey-sergeevich commented on main_service/src/main/java/ru/practicum/main_service/categories/CategoryController.java
> +public class CategoryController {
Можно накинуть аннотацию ломбока и избавиться от конструктора

2022-11-07 12:29 UTC, krylov-sergey-sergeevich commented on main_service/src/main/java/ru/practicum/main_service/categories/CategoryController.java
> +    public List<CategoryDto> findAll(@RequestParam(name = "from", defaultValue = "0")
как то checkstyle поехал, переменные съехали по строкам

2022-11-07 12:29 UTC, krylov-sergey-sergeevich commented on main_service/src/main/java/ru/practicum/main_service/categories/CategoryConverter.java
> +public class CategoryConverter {
Отлично, можете ещё посмотреть в сторону библиотеки MapStruct, она сама мапит поля с одинаковым типом и именованием. https://www.baeldung.com/mapstruct

Применить только у вас не получится. Т.к. тесты не пройдут.
Если будут вопросы как использовать данную библиотеку - можете посмотреть это видео
https://youtu.be/Qczc8ci0ylE?t=409

2022-11-07 12:29 UTC, krylov-sergey-sergeevich commented on main_service/src/main/java/ru/practicum/main_service/categories/CategoryServiceImpl.java
> +public class CategoryServiceImpl implements CategoryService {
Тоже тут можно аннотацию чтобы от конструктора избавиться

2022-11-07 12:29 UTC, krylov-sergey-sergeevich commented on main_service/src/main/java/ru/practicum/main_service/categories/CategoryService.java
> +public interface CategoryService {
Сделано хорошо, но вот лично моя позиция что сервисы если требуется принимают реквест dto а отдают ентити, и если надо превращаем в другие дто в контроллере, но кто то любит отдавать из сервисов сразу dto тут кому как привычнее. Поэтому тут не критика, а скорее мнение =)

2022-11-07 12:29 UTC, krylov-sergey-sergeevich commented on main_service/src/main/java/ru/practicum/main_service/compilations/CompilationServiceImpl.java
> +public class CompilationServiceImpl implements CompilationService {
Аннотацию чтобы без конструктора

2022-11-07 12:29 UTC, krylov-sergey-sergeevich commented on main_service/src/main/java/ru/practicum/main_service/compilations/CompilationServiceImpl.java
> +            Event event = eventRepository.getReferenceById(id);
Вот тут не будет ли слишком много запросов в БД? Нельзя ли сразу все достать, на подумать

2022-11-07 12:29 UTC, krylov-sergey-sergeevich commented on main_service/src/main/java/ru/practicum/main_service/compilations/model/Compilation.java
> +    public boolean equals(Object o) {
У нас есть требование от создателей задачи, что бы в модели не было методов equals и hashCode
Причины:
1. Студенты случай с хибернейтом не проходили
2. Нет причин его использовать,
3. Это может привести к ошибкам

2022-11-07 12:29 UTC, krylov-sergey-sergeevich commented on main_service/src/main/java/ru/practicum/main_service/events/EventController.java
> +public class EventController {
Тоже про конструктор

2022-11-07 12:29 UTC, krylov-sergey-sergeevich commented on main_service/src/main/java/ru/practicum/main_service/events/EventController.java
> +        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Такой паттерн используется несколько раз, не лучше ли объект один раз создать?

2022-11-07 12:29 UTC, krylov-sergey-sergeevich commented on stat_service/src/main/java/ru/practicum/stat_service/stats/StatsRepository.java
> +    @Query("select COUNT(id) from Hit where timestamp>=?1 AND timestamp<=?2 AND uri LIKE ?3")
Почему тут используется ?1 вместо имен переменных?

2022-11-07 12:29 UTC, krylov-sergey-sergeevich commented on stat_service/src/main/java/ru/practicum/stat_service/stats/StatsServiceImpl.java
> +        String app = "main_service";
лучше такие переменные выносить в статику и какой то утилитный класс который их все хранит или переменные приложения

2022-11-07 12:29 UTC, krylov-sergey-sergeevich commented on stat_service/src/main/java/ru/practicum/stat_service/stats/StatsServiceImpl.java
> +        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Опять создаем форматер хотя он уже в этом приложение где-то подобный есть вроде как =)

2022-11-07 14:53 UTC, AlexMAK1 commented on main_service/src/main/java/ru/practicum/main_service/categories/CategoryController.java
> +public class CategoryController {
done

2022-11-07 14:54 UTC, AlexMAK1 commented on main_service/src/main/java/ru/practicum/main_service/categories/CategoryController.java
> +    public List<CategoryDto> findAll(@RequestParam(name = "from", defaultValue = "0")
done

2022-11-07 14:55 UTC, AlexMAK1 commented on main_service/src/main/java/ru/practicum/main_service/categories/CategoryConverter.java
> +public class CategoryConverter {
Ок, посмотрю видео и ознакомлюсь на будущее. Спасибо.

2022-11-07 14:58 UTC, AlexMAK1 commented on main_service/src/main/java/ru/practicum/main_service/categories/CategoryServiceImpl.java
> +public class CategoryServiceImpl implements CategoryService {
done

2022-11-07 14:58 UTC, AlexMAK1 commented on main_service/src/main/java/ru/practicum/main_service/events/EventController.java
> +public class EventController {
done

2022-11-07 15:02 UTC, AlexMAK1 commented on main_service/src/main/java/ru/practicum/main_service/events/EventController.java
> +        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
done

2022-11-07 16:15 UTC, AlexMAK1 commented on stat_service/src/main/java/ru/practicum/stat_service/stats/StatsRepository.java
> +    @Query("select COUNT(id) from Hit where timestamp>=?1 AND timestamp<=?2 AND uri LIKE ?3")
Хороший вопрос. Сравнивал с UserRepository там используется переменная. Здесь не получается реализация в другом виде.

2022-11-07 16:19 UTC, AlexMAK1 commented on stat_service/src/main/java/ru/practicum/stat_service/stats/StatsServiceImpl.java
> +        String app = "main_service";
done

2022-11-07 16:31 UTC, AlexMAK1 commented on stat_service/src/main/java/ru/practicum/stat_service/stats/StatsServiceImpl.java
> +        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
done

2022-11-07 16:32 UTC, AlexMAK1 commented on main_service/src/main/java/ru/practicum/main_service/categories/CategoryService.java
> +public interface CategoryService {
ок, ронял. приму во внимание. спасибо.

2022-11-07 16:32 UTC, AlexMAK1 commented on main_service/src/main/java/ru/practicum/main_service/categories/CategoryService.java
> +public interface CategoryService {
понял)))

2022-11-07 16:32 UTC, AlexMAK1 commented on main_service/src/main/java/ru/practicum/main_service/categories/CategoryService.java
> +public interface CategoryService {
ок. понял, приму во внимание. спасибо.

2022-11-07 16:32 UTC, AlexMAK1 commented on main_service/src/main/java/ru/practicum/main_service/compilations/CompilationServiceImpl.java
> +public class CompilationServiceImpl implements CompilationService {
done

2022-11-07 16:37 UTC, AlexMAK1 commented on main_service/src/main/java/ru/practicum/main_service/events/EventController.java
> +public class EventController {
done

2022-11-07 16:41 UTC, AlexMAK1 commented on main_service/src/main/java/ru/practicum/main_service/compilations/model/Compilation.java
> +    public boolean equals(Object o) {
done

2022-11-07 19:26 UTC, AlexMAK1 commented on main_service/src/main/java/ru/practicum/main_service/compilations/CompilationServiceImpl.java
> +            Event event = eventRepository.getReferenceById(id);
done

2022-11-07 19:30 UTC, AlexMAK1 commented on main_service/Dockerfile
> +COPY target/*.jar app.jar
ок. в чем преимущество такого подхода?

2022-11-08 06:44 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2022-11-08 06:44 UTC, krylov-sergey-sergeevich commented on main_service/src/main/java/ru/practicum/main_service/events/EventServiceImpl.java
> +    public static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Хорошо что теперь везде эту переменную используете, но лучше такие в утилитные классы выносить, на будущее

2022-11-08 06:44 UTC, krylov-sergey-sergeevich commented on main_service/Dockerfile
> +COPY target/*.jar app.jar
По сути прямых плюсов нет, скорее тут говорю о том что такая возможность есть =)

2022-11-08 07:29 UTC, krylov-sergey-sergeevich requested changes
Привет, проверил код в git все ок и потом понял что забыл о моменте с 

"Меня смутило отсутствие схемы бд в файлах схемы, так и запланировано было?" - поэтому вопрос где схема?)

2022-11-08 17:43 UTC, krylov-sergey-sergeevich approved these changes
Вот теперь хорошо

2022-11-12 15:15 UTC, merged